### PR TITLE
Implement 'show modal on question queue accept'

### PR DESCRIPTION
**Pull request by JustinPraas**
When a TA now accepts a student from a 'questions' type queue, he or she will get a modal indicating the name of the accepted student, while also having the ability to remind said student.

### CODE REVIEW

**Comment by JustinPraas** [comment]
Shall we merge this for now and add the timer later? @harindup suggested to use hooks for the timing behavior of the modals, but I'm not familiarized with them yet.

**Comment by harindup** [comment]
> Shall we merge this for now and add the timer later? @harindup suggested to use hooks for the timing behavior of the modals, but I'm not familiarized with them yet.

@JustinPraas I meant that this is a good use for Hooks, but sadly you can't use them in class components. Making the component functional can be annoying at this point, so you can just not use Hooks for this.

**Comment by JustinPraas** [comment]
I see. Well in that case, shall we merge this?

**Comment by VriesDeRick** [comment]
I'm fine with including this in tonight's deployment (with tons of security fixes as well) if the code is okay. Sadly, no one has reviewed it yet. Maybe @harindup can do so?

**Pull request merged**
